version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - run:
          name: Deploy to EC2 with HTTPS
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS /bin/bash -c '
              sudo apt update
              sudo apt install -y certbot
              sudo certbot certonly --standalone -d 54.234.188.62.nip.io --non-interactive --agree-tos --email x16134672@student.ncirl.ie || true
              sudo mkdir -p /home/ubuntu/certs
              sudo cp /etc/letsencrypt/live/54.234.188.62.nip.io/privkey.pem /home/ubuntu/certs/ || true
              sudo cp /etc/letsencrypt/live/54.234.188.62.nip.io/fullchain.pem /home/ubuntu/certs/ || true
              sudo chown ubuntu:ubuntu /home/ubuntu/certs/*
              sudo chmod 644 /home/ubuntu/certs/*
              rm -rf SimpleApplication
              git clone https://github.com/DevOpsMyCA/SimpleApplication.git
              cd SimpleApplication
              npm install
              npm install https
              sudo setcap "cap_net_bind_service=+ep" $(which node)
              sudo pm2 stop example_app || true
              sudo pm2 start ./bin/www --name example_app
              sudo pm2 save
            '
