version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS << 'EOF'
              rm -rf SimpleApplication
              git clone https://github.com/DevOpsMyCA/SimpleApplication.git
              cd SimpleApplication
              npm install
              pm2 stop example_app || true
              pm2 start ./bin/www --name example_app
              pm2 save
            EOF
