version: 2.1
 
 workflows:
   version: 2
   build:
     jobs:
       - build:
           filters:
             branches:
               only:
                 - main
       - deploy:
           filters:
             branches:
               only:
                 - main
           requires:
             - build
 
 jobs:
   build:
     working_directory: ~/SimpleApplication
     docker:
       - image: node:20
     steps:
       - checkout
       - run:
           name: update-npm
           command: 'sudo npm install -g npm@latest'
           command: 'npm install -g npm@latest'  # Removed `sudo` since it's unnecessary
       - restore_cache:
           key: dependency-cache-{{ checksum "package-lock.json" }}
       - run:
           name: install-npm-dependencies
           command: npm install
       - save_cache:
           key: dependency-cache-{{ checksum "package-lock.json" }}
           paths:
             - ./node_modules
 
   deploy:
     docker:
       - image: node:20
     steps:
       - run:
           name: Setup SSH Key for EC2
           command: |
             echo "$EC2_PRIVATE_KEY" > ~/.ssh/id_rsa
             chmod 400 ~/.ssh/id_rsa
       - run:
           name: Deploy-Application
           command: |
             ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_DNS "rm -rf SimpleApplication && git clone https://github.com/DevOpsMyCA/SimpleApplication && cd SimpleApplication && source deploy.sh"
