version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: cimg/node:20.17.0
    steps:
      - run:
          name: Deploy to EC2 with HTTPS
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS << 'EOF'
              sudo apt update
              sudo apt install -y certbot
              sudo certbot certonly --standalone -d 54.234.188.62.nip.io --non-interactive --agree-tos --email x16134672@student.ncirl.ie || true
              rm -rf SimpleApplication
              git clone https://github.com/DevOpsMyCA/SimpleApplication.git
              cd SimpleApplication
              npm install
              npm install https
              sudo pm2 stop example_app || true
              sudo pm2 start ./bin/www --name example_app
              sudo pm2 save
            EOF
